import requests

# Insert URL to send request to
r = requests.get("https://api.github.com/repos/dward2/BME547/braxnches")
print(r)
print(type(r))
print(r.text)
if r.status_code == 200:
    answer = r.json()
    print(type(answer))
    for branch in answer:
        print(branch['name'])
else:
    print("Bad request: {}".format(r.text))
    # Response code is generated by website we are sending a request to

output_info= {"name": "Nikhil Gadiraju",
              "net_id": "nvg6",
              "e-mail": "nikhil.gadiraju@duke.edu"}

r = requests.post("http://vcm-21170.vm.duke.edu:5000/student",
                  json=output_info)
print(r)
# Entering a URL into a browser creates a get request;
# browsers create get requests. You cannot make a post
# request in a browser
r = requests.get("http://vcm-21170.vm.duke.edu:5000/list")
print(r.text)

message = {'user': 'iww','message': 'hello'}
r = requests.post("http://vcm-21170.vm.duke.edu:5001/add_message", json=message)
